### ISSUE TITLE
tile stitch raster: CLibJPEGImageReaderSpi could not be instantiated

### ISSUE THREAD

**Issue by tobwen** [jericks/geoc#7]
## report
```
Exception in thread "main" java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReaderSpi could not be instantiated
```
<details>
<summary>expand for the error message</summary>

```
Exception in thread "main" java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReaderSpi could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
        at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:188)
        at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
        at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
        at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.lambda$createCallStaticSite$2(CallSiteArray.java:65)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:63)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:156)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at geoscript.layer.ImageTile.getImage(ImageTile.groovy:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:85)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
        at geoscript.layer.ImageTileLayer$_getRaster_closure1.doCall(ImageTileLayer.groovy:44)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1029)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2318)
        at org.codehaus.groovy.runtime.dgm$199.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:226)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at geoscript.layer.ImageTileLayer.getRaster(ImageTileLayer.groovy:31)
        at geoscript.layer.ImageTileLayer$getRaster.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.geocommands.tile.StitchRasterCommand.execute(StitchRasterCommand.groovy:55)
        at org.geocommands.tile.StitchRasterCommand$execute$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
        at org.geocommands.App.main(App.groovy:85)
Caused by: java.lang.IllegalArgumentException: vendorName == null!
        at java.desktop/javax.imageio.spi.IIOServiceProvider.<init>(IIOServiceProvider.java:76)
        at java.desktop/javax.imageio.spi.ImageReaderWriterSpi.<init>(ImageReaderWriterSpi.java:233)
        at java.desktop/javax.imageio.spi.ImageReaderSpi.<init>(ImageReaderSpi.java:212)
        at com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReaderSpi.<init>(CLibJPEGImageReaderSpi.java:80)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
        ... 54 more
```
</details>

## steps to reproduce
```
curl -kJLOR https://ivansanchez.gitlab.io/Leaflet.TileLayer.MBTiles/demo/countries-raster.mbtiles
geoc tile stitch raster -l countries-raster.mbtiles -z 1 -o countries.tif
```

## my system
- Debian 10, AMD64
- prebuilt _geoc_ from github in v0.13.0
- openjdk-11-jre-headless v11.0.6+10-1~deb10u1

**Comment by jericks** [comment]
You need to install Java Advanced Imaging and ImageIO.  Something like this might work:

sudo apt-get install libjai-imageio-core-java

I need better installation instructions.

**Comment by tobwen** [comment]
It needs _libopenimageio2.0_ in terms of _OpenJDK_. But it's built against _GDAL_ in one of its dependencies (_libopencv-imgcodecs3.2_) and it'll break my local backport. Since also _libopencv-videoio3.2_ will be pulled, I'm getting a ton of audio libraries, like _libmp3_ on my server.

I'll try this in a container or chroot.

**Comment by tobwen** [comment]
Even after rebuilding it, I'm getting
```Provider com.sun.media.imageioimpl.plugins.jpeg.CLibJPEGImageReaderSpi could not be instantiated```

Seems like it's not compatible with _OpenJDK_.

**Comment by tobwen** [comment]
I've tried to build it on my system. Now I'm getting:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.geotools.image.ImageWorker (file:/root/.m2/repository/org/geocommands/geocommands/0.14.0-SNAPSHOT/geoc-0.14.0-SNAPSHOT/lib/gt-coverage-24-20200528.100016-44.jar) to constructor com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi()
WARNING: Please consider reporting this to the maintainers of org.geotools.image.ImageWorker
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
- Unable to render RenderedOp for this operation.
```

**Comment by jericks** [comment]
I tested geoc in Ubuntu 16 and 18 with OpenJDK 8.  I think I had to install libjai (https://packages.ubuntu.com/search?keywords=libjai-core-java).

**Comment by tobwen** [comment]
Yeah, there's no such thing in Debian. It has been dropped a long time ago and already then, it 
 was non-free: https://packages.debian.org/de/jessie/libjai-core-java

Xenial also is 4 years old, it's LTS, but the packages didn't make it in a newer version of Ubuntu. _ORACLE_ has left a lot of scorched earth behind.

I tried to talk to the #java guys in Freenode, but they don't give any support since only the coder can change it. I also think it's not a _geoc_ issue. Should I better file an issue at _geotools_?

### Edit
1. I just saw, _geoserver_ ships with a "pure Java version of JAI": https://geoserver.geo-solutions.it/edu/en/install_run/jai_io_install.html
2. In `geocommands-0.14.0-SNAPSHOT-app/geoc-0.14.0-SNAPSHOT/lib` there's also a _jai_core-1.1.3.jar_ - can't I use this somehow?
3. _OpenStreetMap's JOSM_ had the same problems in the past. They missed an `add export`: https://josm.openstreetmap.de/ticket/17933

### Workarounds
1. For god's sake, _NVIDIA_ is providing an _OpenJDK_ fork on stable and future _Debian_! It even works without _CUDA_! https://packages.debian.org/buster/nvidia-openjdk-8-jre
2. Containers (_Podman_, _Docker_, etc.) https://github.com/docker-library/openjdk/blob/master/8/jre/slim/Dockerfile

### My solution
Inspired by the official container solution, here's my way (works even for non-root users and with other JREs installed):
``` sh
# define variables (might version and build need to be updated in future)
JAVA_VERSION=8u252
JAVA_BUILD=b09
JAVA_FN="OpenJDK8U-jre_x64_linux_${JAVA_VERSION}${JAVA_BUILD}.tar.gz"
JAVA_HOME="~/.local/bin/OpenJDK/${JAVA_VERSION}-${JAVA_BUILD}"

# create the environment, download and extract the prebuilt binaries
mkdir --parents "$JAVA_HOME"
wget --output-document="$JAVA_FN" "https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk${JAVA_VERSION}-${JAVA_BUILD}/${JAVA_FN}"
tar --extract --file "$JAVA_FN" --directory "$JAVA_HOME" --strip-components 1 --no-same-owner

# promote JAVA_HOME's new location for this session
export JAVA_HOME

# maybe add it to your ~/.bashrc or ~/.profile
echo "export JAVA_HOME=\"$JAVA_HOME\"" >> ~/.bashrc
# or
printf 'export JAVA_HOME=%q\n' "$JAVA_HOME" >> ~/.bashrc

# or set up an alias
alias geoc="$JAVA_HOME/bin/java -jar /root/geoc-app-0.13.0.jar"

```
### Conclusion
So as it seems, _OpenJDK v11_ is too new for _geotools_. You might really state this on the website for non-advanced users like I am.

**Comment by tobwen** [comment]
I'm going mad... `geoc-app-0.13.0.jar` was the problem! It works with `geocommands-0.13.0-app.zip` - even with _OpenJDK v11_!

It seems like the export or something is really missing in the app-jar. Could you have a look, please?

**Comment by tobwen** [comment]
Oh! You already fixed it: https://github.com/jericks/geoc/commit/105b60ff4b423ea77cf4ab4fcc70cb0d0a37886e

Your commit message is crazy :-)

**Comment by tobwen** [comment]
Sorry for messing around, but it still doesn't work as expected. Neither with v11 nor with v8. I think I'm giving up.

**Comment by tobwen** [comment]
Okay, after doing some extensive testing of _OpenJDK v8-11 JRE_, version **8** seems to be the only one, which works without problems with https://github.com/jericks/geoc/commit/105b60ff4b423ea77cf4ab4fcc70cb0d0a37886e, which will be part of upcoming _v0.14_,.

Previous to _v0.14_, only `geocommands-0.xx.0-app.zip` is working, but only up to _OpenJDK **8**_

**Comment by tobwen** [comment]
@jericks Could you be so nice and build a _v0.14_ in its current state? Then I can test it and close this :-)

**Comment by jericks** [comment]
https://github.com/jericks/geoc/releases/tag/0.14.0

**Comment by tobwen** [comment]
Thanks, it works with my the NVIDIA-build from https://github.com/jericks/geoc/issues/7#issuecomment-635773736 (OpenJDK/9.+8u77~9.2.148-7)

but not with the _AdoptOpenJDK_'s one (OpenJDK/8u252-b09): `All factories fail for the operation "ImageWrite"`
